package com.grimoire.application.core.ecs;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * Manages entity lifecycle with primitive int IDs.
 *
 * <p>
 * Entities are primitive ints generated by an {@link AtomicInteger}. A boolean
 * array tracks which IDs are alive. No String or UUID overhead.
 * </p>
 *
 * <p>
 * <strong>Thread-safety:</strong> This class must only be accessed from the
 * single-threaded game loop. Register as a singleton at the assembly layer.
 * </p>
 */
public class EntityManager {

    /** Maximum number of concurrent entities. */
    public static final int MAX_ENTITIES = 100_000;

    /** Monotonic entity ID generator. */
    private final AtomicInteger nextId = new AtomicInteger(0);

    /** Alive flags indexed by entity ID. */
    private final boolean[] alive = new boolean[MAX_ENTITIES];

    /**
     * High-water mark for active entity IDs (exclusive upper bound for iteration).
     */
    private int maxAliveId;

    /**
     * Creates a new entity with a unique int ID.
     *
     * @return the entity ID
     * @throws IllegalStateException
     *             if the entity limit is exceeded
     */
    public int createEntity() {
        int entityId = nextId.getAndIncrement();
        if (entityId >= MAX_ENTITIES) {
            throw new IllegalStateException("Entity limit exceeded: " + MAX_ENTITIES);
        }
        alive[entityId] = true;
        if (entityId >= maxAliveId) {
            maxAliveId = entityId + 1;
        }
        return entityId;
    }

    /**
     * Destroys an entity.
     *
     * @param entityId
     *            the entity ID
     */
    public void destroyEntity(int entityId) {
        if (entityId >= 0 && entityId < MAX_ENTITIES) {
            alive[entityId] = false;
        }
    }

    /**
     * Checks if an entity exists.
     *
     * @param entityId
     *            the entity ID
     * @return true if the entity exists
     */
    public boolean exists(int entityId) {
        return entityId >= 0 && entityId < MAX_ENTITIES && alive[entityId];
    }

    /**
     * Returns the high-water mark for iteration.
     *
     * @return the exclusive upper bound of entity IDs ever created
     */
    public int getMaxEntityId() {
        return maxAliveId;
    }

    /**
     * Returns the alive array for direct iteration by systems.
     *
     * @return the alive flags
     */
    public boolean[] getAlive() {
        return alive;
    }
}
